#!/bin/bash

memory="$(free -h | awk '/^Mem/ {print $3"/"$2}' | sed s/i//g)"
# memory="$(free -h | awk '/^Mem/ {print $3"/"$2}' | sed s/i//g) "
# echo "^c#ffffff^  ^d^$memory"
echo " 🎫$memory"
#echo "   $memory"
