#!/bin/bash

vol(){
  pamixer --get-volume
}

str(){
  echo "$1"
}

case $BLOCK_BUTTON in
    1) pamixer -t ;;
    4) pamixer -i 2;; 
    5) pamixer -d 2;;
esac

if [ "$(pamixer --get-mute)" = "true" ]; then
  str "  "
  exit 0
fi

v=$(vol)
if [ "$v" -eq "100" ]; then
  str "100% "
elif [ "$v" -ge "30" ]; then
  str "$v%"
else 
  str "$v%"
fi
