#!/bin/bash

# Detecta si el puerto de audífonos está activo en ALSA
if amixer -c 0 contents | grep -A 2 -i "headphone" | grep -q "values=on"; then
  ICONO="🎧"
else
  ICONO="📢"
fi

vol(){
  pamixer --get-volume
}

str(){
  echo "$1"
}

case $BLOCK_BUTTON in
    1) pamixer -t ;;
    4) pamixer -i 2 ;; 
    5) pamixer -d 2 ;;
esac

if [ "$(pamixer --get-mute)" = "true" ]; then
  str "🔇Mut"
  exit 0
fi

v=$(vol)
if [ -z "$v" ]; then v=0; fi

if [ "$v" -ge "100" ]; then
  str "${ICONO}Max"
else 
  str "${ICONO}$v%"
fi
